# Generated by Django 2.2.7 on 2020-02-14 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.Catagory'),
        ),
    ]
