# Generated by Django 2.2.7 on 2020-02-14 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_catagory_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name': 'catagory', 'verbose_name_plural': 'catagories'},
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='parent',
        ),
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
