# Generated by Django 2.2.7 on 2020-02-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200215_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='publish', max_length=12000),
        ),
    ]
