# Generated by Django 2.2.7 on 2020-02-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200215_0209'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Prod',
        ),
    ]
