# Generated by Django 2.2.7 on 2020-02-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200215_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='price',
            field=models.IntegerField(default=1, max_length=9999999),
            preserve_default=False,
        ),
    ]
