# Generated by Django 2.2.7 on 2020-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_prod_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='price',
            field=models.IntegerField(),
        ),
    ]
