# Generated by Django 2.2.7 on 2020-02-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200215_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=120)),
                ('Phone', models.IntegerField()),
                ('Message', models.TextField(max_length=1200)),
            ],
        ),
    ]
