# Generated by Django 2.2.7 on 2020-02-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contactform', 'verbose_name_plural': 'contact'},
        ),
        migrations.RenameField(
            model_name='catagory',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='prod',
            old_name='name',
            new_name='title',
        ),
    ]
