# Generated by Django 2.2.7 on 2020-02-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200215_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
