# Generated by Django 2.2.7 on 2021-01-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200419_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='value',
        ),
    ]
